#!/usr/bin/env python3
"""Generate or extend a machine-local settings override file.

Every setting is written live, at its current tracked value, ready to edit in
place; nothing needs to be uncommented before it takes effect. Comment a line
out to release that key back to following the tracked default instead of
pinning it to what it was when generated.

Default behaviour is additive and safe to run any number of times: it adds
any setting that exists in the project's tracked vars files but is not yet
mentioned anywhere in the output file (live or commented out), appended in a
clearly dated section. A line that is already in the file, live or commented,
is never touched. Nothing new to add means nothing is written at all, so
running this twice in a row with no upstream change leaves the file
byte-for-byte identical.

Because every value is live, a setting this file mentions no longer follows
the tracked default if that default later changes upstream: the local value
always wins once it is here. Comment out a key (or delete its line) to let it
follow the tracked default again.

--force replaces the file from scratch instead, which is the only way this
script discards local edits. The previous file is copied to <output>.bak
first, since git does not track or back up this file.

Text is copied from the source vars files rather than round-tripped through a
YAML parser, so the comments, ordering and formatting of those files survive
intact and the generated template cannot drift from what it documents.

Not handled on purpose: a key that disappears from the tracked vars files
(renamed or removed) is left in the local file rather than pruned. Cleaning
those up is a manual, reviewed action, not an automatic side effect of adding
new ones.

Also not handled by the sync: a top-level key that is already live, such as
`kvm_hypervisors` or `kvm_instance_definitions`, is a list of mappings, and
once it exists at all the sync leaves its contents alone even if the tracked
template later grows a nested field that no item in the local list has (a new
per-host key, say). That is correct for the sync's job, which is to never
touch a line that is already there, but it means the full field list for one
of those entries can stop being visible in the local file after it is first
customised. --reference is the answer: it writes a complete, always-current
catalogue to a separate, disposable file, so that reference is never lost.
"""

import argparse
import datetime
import os
import re
import shutil
import sys

LIVE_KEY_RE = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*):')
COMMENTED_KEY_RE = re.compile(r'^#\s?([A-Za-z_][A-Za-z0-9_]*):')
BANNER_RE = re.compile(r'^# \d+\.\s+(.*)$')
SKIP = ('no-local-overrides.yml',)

HEADER = """---
# Machine-specific settings for this host. Generated by `make settings`.
#
# HOW THIS FILE IS USED
#   playbook.yml loads the tracked settings files first, then this one last.
#   Every key below is LIVE and currently set to the tracked default's value,
#   so it overrides the same key in those files with an identical copy of it.
#   Edit a value in place to make it actually differ on this machine.
#
# THE THREE RULES
#   1. A live key here always wins, even if it matches the tracked default
#      exactly: if that default changes later, this file will not follow it
#      until you update the value here too. Comment out or delete a line to
#      let that key track the tracked default again instead of pinning it.
#   2. Overriding replaces the WHOLE value, it does not merge. A list such as
#      {list_example} must list every entry you want, because the
#      tracked list is replaced outright, not added to.
#   3. Once a key lives here, edit it HERE. The same key in a tracked file is
#      ignored from then on. Each run prints which keys this file supplies.
#
# This file matches *.local.yml and is gitignored, so nothing in it is ever
# committed. Git therefore does not back it up either: keep your own copy of
# anything you cannot recreate.
#
# Running `make settings` again only ADDS settings that are new upstream and
# not yet mentioned below; it never changes a line already here, and does
# nothing at all if there is nothing new to add.
# To start over from a clean template instead: make settings FORCE=1
# (that overwrites this file; a copy is saved next to it as <file>.bak first)
"""

REFERENCE_HEADER = """---
# Complete settings reference. Generated by `make settings-reference`.
#
# This file is NOT read by playbook.yml. It is not an override file at all:
# it exists purely so every setting, including every field of a list entry
# such as {list_example}, has somewhere to be looked up in full, even after
# the same top-level key has been customised in vars/settings.local.yml and
# stopped showing its full field list there.
#
# To change a setting, edit vars/settings.local.yml, not this file. Copy the
# field names you need from here into it.
#
# This file is regenerated from scratch every time and safe to delete:
# make settings-reference
"""

NEW_SECTION_HEADER = """
# =============================================================================
# New settings found on {date} (added automatically by `make settings`)
# Nothing above this line was changed. These are live, set to the current
# tracked default's value; edit one to make it actually differ here, or
# comment it out to let it keep following the tracked default instead.
# =============================================================================
"""


def blocks(path):
    """Yield (banner, key, [lines]) for every top-level key in a vars file."""
    with open(path, encoding='utf-8') as handle:
        lines = handle.read().split('\n')
    banner, out, current = None, [], None
    for line in lines:
        match = BANNER_RE.match(line)
        if match:
            banner = match.group(1)
            continue
        if line.startswith('#') or not line.strip():
            continue
        key_match = LIVE_KEY_RE.match(line)
        if key_match:
            if current is not None:
                out.append(current)
            current = (banner, key_match.group(1), [line])
        elif current is not None and (line.startswith(' ') or line.startswith('-')):
            current[2].append(line)
    if current is not None:
        out.append(current)
    return out


def existing_top_level_keys(path):
    """Keys already mentioned in a local settings file, live or commented.

    A key counts as covered the moment it appears at column zero, whether as
    a real override (`key: value`) or as an untouched placeholder
    (`# key: value`). Only that top-level form is checked: an indented line
    such as `#   - name: ...` inside a list is never mistaken for one.
    """
    keys = set()
    with open(path, encoding='utf-8') as handle:
        for line in handle:
            match = LIVE_KEY_RE.match(line) or COMMENTED_KEY_RE.match(line)
            if match:
                keys.add(match.group(1))
    return keys


def collect(vars_dir):
    """Return (sources, found) for every settings file in vars_dir.

    found is a list of (source_filename, (banner, key, lines)) in source order.
    """
    sources = sorted(
        f for f in os.listdir(vars_dir)
        if f.endswith('.yml') and not f.endswith('.local.yml') and f not in SKIP
        and not f.endswith('.example'))
    found = []
    for name in sources:
        found.extend((name, block) for block in blocks(os.path.join(vars_dir, name)))
    return sources, found


def render(sources, found, only_keys=None, comment_out=False):
    """Render '# From <file>' groups, optionally restricted to only_keys.

    comment_out=False (the default) writes each value line exactly as it
    appears in the tracked file: live, ready to take effect immediately.
    comment_out=True prefixes every value line with '# ' instead, for the
    read-only --reference catalogue, which is never meant to take effect.
    """
    body, total = [], 0
    for name in sources:
        entries = [block for src, block in found
                   if src == name and (only_keys is None or block[1] in only_keys)]
        if not entries:
            continue
        body.append('\n# ' + '=' * 75)
        body.append(f'# From {name}')
        body.append('# ' + '=' * 75)
        seen_banner = None
        for banner, _key, lines in entries:
            if banner and banner != seen_banner:
                body.append(f'\n# --- {banner} ---')
                seen_banner = banner
            if comment_out:
                body.extend('# ' + line if line else '#' for line in lines)
            else:
                body.extend(lines)
            total += 1
    return body, total


def write_fresh(args, sources, found, header=HEADER, comment_out=False):
    if os.path.exists(args.output) and (args.force or args.reference):
        backup = args.output + '.bak'
        shutil.copy2(args.output, backup)
        print(f"Backed up existing {args.output} to {backup}.")

    list_example = next((key for _, (_, key, lines) in found if len(lines) > 1),
                         'a list value')
    body, total = render(sources, found, comment_out=comment_out)
    content = header.format(list_example=list_example) + '\n'.join(body)
    with open(args.output, 'w', encoding='utf-8') as handle:
        handle.write(content.rstrip('\n') + '\n')
    if args.reference:
        print(f"Wrote {args.output} with {total} settings, all commented out.")
        print("This is a reference copy; playbook.yml does not read it.")
    else:
        print(f"Wrote {args.output} with {total} settings, live at their "
              "current tracked default value.")
        print("Comment out a line to let that key follow the tracked "
              "default instead of pinning it.")


def sync_additions(args, sources, found):
    existing_keys = existing_top_level_keys(args.output)
    all_keys = {key for _, (_, key, _lines) in found}
    missing_keys = sorted(all_keys - existing_keys)

    if not missing_keys:
        print(f"{args.output} already covers every current setting. No changes made.")
        return

    body, total = render(sources, found, only_keys=set(missing_keys))
    section = NEW_SECTION_HEADER.format(date=datetime.date.today().isoformat())
    with open(args.output, 'a', encoding='utf-8') as handle:
        handle.write(section)
        handle.write('\n'.join(body).lstrip('\n') + '\n')
    print(f"Added {total} new setting(s) to {args.output}, live at their "
          "current tracked default value:")
    for key in missing_keys:
        print(f"  {key}")
    print("Nothing else in the file was changed.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--vars-dir', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--force', action='store_true',
                         help='Replace the file from scratch instead of only '
                              'adding new settings. Backs up the old one first.')
    parser.add_argument('--reference', action='store_true',
                         help='Write a complete, always-fresh reference copy '
                              'instead of an override file. Ignores --force '
                              'and any existing sync state; always a full '
                              'rewrite, backed up first if the file exists.')
    args = parser.parse_args()

    sources, found = collect(args.vars_dir)
    if not sources:
        sys.stderr.write(f"No settings files found in {args.vars_dir}.\n")
        return 1

    if args.reference:
        write_fresh(args, sources, found, header=REFERENCE_HEADER, comment_out=True)
    elif os.path.exists(args.output) and not args.force:
        sync_additions(args, sources, found)
    else:
        write_fresh(args, sources, found)
    return 0


if __name__ == '__main__':
    sys.exit(main())
