#!/usr/bin/env python3
"""Generate or extend a machine-local settings override file.

Every setting is written live, at its current tracked value, ready to edit in
place; nothing needs to be uncommented before it takes effect. Comment a line
out to release that key back to following the tracked default instead of
pinning it to what it was when generated.

Default behaviour is additive and safe to run any number of times: it adds
any setting that exists in the project's tracked vars files but is not yet
mentioned anywhere in the output file (live or commented out), appended in a
clearly dated section. A line that is already in the file, live or commented,
is never touched. Nothing new to add means nothing is written at all, so
running this twice in a row with no upstream change leaves the file
byte-for-byte identical.

Because every value is live, a setting this file mentions no longer follows
the tracked default if that default later changes upstream: the local value
always wins once it is here. Comment out a key (or delete its line) to let it
follow the tracked default again.

--force replaces the file from scratch instead, which is the only way this
script discards local edits. The previous file is copied to <output>.bak
first, since git does not track or back up this file.

Text is copied from the source vars files rather than round-tripped through a
YAML parser, so ordering, formatting, and each setting's own comment survive
intact and the generated template cannot drift from what it documents. A key
blanked to [] or {} carries a worked example immediately below it in the
tracked file (a real host, a real instance, ...); that travels here too, as
a comment right under the key it documents, since a bare [] gives no hint of
the shape a real value should take the way a scalar's own inline comment
does.

Not handled on purpose: a key that disappears from the tracked vars files
(renamed or removed) is left in the local file rather than pruned. Cleaning
those up is a manual, reviewed action, not an automatic side effect of adding
new ones.

Also not handled by the sync: a top-level key that is already live, such as
`kvm_hypervisors` or `kvm_instance_definitions`, is a list of mappings, and
once it exists at all the sync leaves its contents (and the worked example
comment it was generated with) alone even if the tracked template later
grows a nested field that no item in the local list has (a new per-host
key, say). The worked example shows the fields that existed when this file
was generated or last synced, not necessarily every field that exists now -
for the current, authoritative list, read the tracked vars file it comes
from.

A project's real secrets file (local-secrets.yml / local_secrets.yml, per
the two spellings this repository's .gitignore already treats as secrets)
is never scanned as a source, no matter what is in vars_dir: it holds real
credential values once an operator has set it up, and a project that loads
it does so through its own include_vars task, independent of and with
higher precedence than settings.local.yml. Copying its keys in here would
duplicate a live secret into a second file and create a copy that looks
editable but is silently ignored at runtime - worse than not generating
anything for it at all.
"""

import argparse
import datetime
import os
import re
import shutil
import sys

LIVE_KEY_RE = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*):')
COMMENTED_KEY_RE = re.compile(r'^#\s?([A-Za-z_][A-Za-z0-9_]*):')
BANNER_RE = re.compile(r'^# \d+\.\s+(.*)$')
LIST_VALUE_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*:\s*\[\]')
# Real secrets files, never a settings source - see the module docstring.
SKIP = ('local-secrets.yml', 'local_secrets.yml')


HEADER = """---
# Machine-specific settings for this host. Generated by `make settings`.
#
# HOW THIS FILE IS USED
#   playbook.yml loads the tracked settings files first, then this one last.
#   Every key below is LIVE and currently set to the tracked default's value,
#   so it overrides the same key in those files with an identical copy of it.
#   Edit a value in place to make it actually differ on this machine.
#
# THE THREE RULES
#   1. A live key here always wins, even if it matches the tracked default
#      exactly: if that default changes later, this file will not follow it
#      until you update the value here too. Comment out or delete a line to
#      let that key track the tracked default again instead of pinning it.
#   2. Overriding replaces the WHOLE value, it does not merge. A list such as
#      {list_example} must list every entry you want, because the
#      tracked list is replaced outright, not added to.
#   3. Once a key lives here, edit it HERE. The same key in a tracked file is
#      ignored from then on. Each run prints which keys this file supplies.
#
# This file matches *.local.yml and is gitignored, so nothing in it is ever
# committed. Git therefore does not back it up either: keep your own copy of
# anything you cannot recreate.
#
# Running `make settings` again only ADDS settings that are new upstream and
# not yet mentioned below; it never changes a line already here, and does
# nothing at all if there is nothing new to add.
# To start over from a clean template instead: make settings FORCE=1
# (that overwrites this file; a copy is saved next to it as <file>.bak first)
"""

NEW_SECTION_HEADER = """
# =============================================================================
# New settings found on {date} (added automatically by `make settings`)
# Nothing above this line was changed. These are live, set to the current
# tracked default's value; edit one to make it actually differ here, or
# comment it out to let it keep following the tracked default instead.
# =============================================================================
"""


def blocks(path):
    """Yield (banner, key, [lines]) for every top-level key in a vars file.

    A key's own worked example, when one immediately follows with no blank
    line in between (the "Example (was the live default...)" comment block
    every blanked [] / {} key carries), travels with it: it documents the
    shape of that exact key, not the file in general, and settings.local.yml
    is where an operator has to know what to type.
    """
    with open(path, encoding='utf-8') as handle:
        lines = handle.read().split('\n')
    banner, out, current = None, [], None
    i = 0
    while i < len(lines):
        line = lines[i]
        match = BANNER_RE.match(line)
        if match:
            banner = match.group(1)
            i += 1
            continue
        # A comment is a comment regardless of indentation - YAML gives '#'
        # that meaning at any column. Checking only line.startswith('#')
        # missed an indented one (the "add a second host" example under
        # kvm_hypervisors, indented to read as nested prose) and let it get
        # swallowed as if it were literal continuation content of the
        # preceding key.
        if line.lstrip().startswith('#') or not line.strip():
            i += 1
            continue
        key_match = LIVE_KEY_RE.match(line)
        if key_match:
            if current is not None:
                out.append(current)
            block_lines = [line]
            i += 1
            # Only ever an exact "Example (was the live default..." block:
            # that sentinel is how every one of these was authored, always
            # immediately under the key it documents, so matching it exactly
            # is precise. A generic "any following comment belongs to this
            # key" rule is not: an ad-hoc explanatory note that precedes the
            # NEXT key, not a worked example of THIS one, sits in exactly
            # the same position and would be attributed to the wrong key.
            if (
                i < len(lines)
                and lines[i].strip().startswith('# Example (was the live default')
            ):
                while i < len(lines) and lines[i].lstrip().startswith('#'):
                    block_lines.append(lines[i])
                    i += 1
            current = (banner, key_match.group(1), block_lines)
            continue
        elif current is not None and (line.startswith(' ') or line.startswith('-')):
            current[2].append(line)
        i += 1
    if current is not None:
        out.append(current)
    return out


def existing_top_level_keys(path):
    """Keys already mentioned in a local settings file, live or commented.

    A key counts as covered the moment it appears at column zero, whether as
    a real override (`key: value`) or as an untouched placeholder
    (`# key: value`). Only that top-level form is checked: an indented line
    such as `#   - name: ...` inside a list is never mistaken for one.
    """
    keys = set()
    with open(path, encoding='utf-8') as handle:
        for line in handle:
            match = LIVE_KEY_RE.match(line) or COMMENTED_KEY_RE.match(line)
            if match:
                keys.add(match.group(1))
    return keys


def collect(vars_dir):
    """Return (sources, found) for every settings file in vars_dir.

    found is a list of (source_filename, (banner, key, lines)) in source order.
    """
    sources = sorted(
        f for f in os.listdir(vars_dir)
        if f.endswith('.yml') and not f.endswith('.local.yml') and f not in SKIP
        and not f.endswith('.example'))
    found = []
    for name in sources:
        found.extend((name, block) for block in blocks(os.path.join(vars_dir, name)))
    warn_on_duplicate_keys(found)
    return sources, found


def warn_on_duplicate_keys(found):
    """Warn, but do not fail, when the same key is defined in two source files.

    Ansible's own vars_files loading would silently let the later file win,
    so this is not this script's bug to fix - but generating a local override
    for a key without knowing it is ambiguous upstream is worth flagging
    loudly rather than passing through quietly.
    """
    by_key = {}
    for src, (_banner, key, _lines) in found:
        by_key.setdefault(key, []).append(src)
    for key, srcs in sorted(by_key.items()):
        if len(srcs) > 1:
            sys.stderr.write(
                f"WARNING: {key} is defined in more than one tracked vars "
                f"file: {', '.join(srcs)}. Ansible's own vars_files loading "
                "will silently prefer whichever loads last; fix the "
                "duplicate in the tracked files rather than relying on "
                "settings.local.yml to paper over it.\n")


def render(sources, found, only_keys=None):
    """Render '# From <file>' groups, optionally restricted to only_keys.

    Each value, its own inline comment, and its own worked example (if one
    immediately follows it in the tracked file) are written exactly as they
    appear there: live, ready to take effect immediately, documented right
    where it has to be read.
    """
    body, total = [], 0
    for name in sources:
        entries = [block for src, block in found
                   if src == name and (only_keys is None or block[1] in only_keys)]
        if not entries:
            continue
        body.append('\n# ' + '=' * 75)
        body.append(f'# From {name}')
        body.append('# ' + '=' * 75)
        seen_banner = None
        for banner, _key, lines in entries:
            if banner and banner != seen_banner:
                body.append(f'\n# --- {banner} ---')
                seen_banner = banner
            body.extend(lines)
            total += 1
    return body, total


def write_fresh(args, sources, found):
    if os.path.exists(args.output) and args.force:
        backup = args.output + '.bak'
        shutil.copy2(args.output, backup)
        print(f"Backed up existing {args.output} to {backup}.")

    # A key with genuine multi-line content is the best example (its shape is
    # visible right there); every tracked file in this repository blanks
    # composites to a single-line [] instead, so fall back to naming any
    # blank list-typed key by name rather than the generic, unhelpful
    # "a list value" that used to show up here once no file had one anymore.
    list_example = next(
        (key for _, (_, key, lines) in found if len(lines) > 1),
        None,
    ) or next(
        (key for _, (_, key, lines) in found if LIST_VALUE_RE.match(lines[0])),
        'a list value',
    )
    body, total = render(sources, found)
    content = HEADER.format(list_example=list_example) + '\n'.join(body)
    with open(args.output, 'w', encoding='utf-8') as handle:
        handle.write(content.rstrip('\n') + '\n')
    print(f"Wrote {args.output} with {total} settings, live at their "
          "current tracked default value.")
    print("Comment out a line to let that key follow the tracked "
          "default instead of pinning it.")


def sync_additions(args, sources, found):
    existing_keys = existing_top_level_keys(args.output)
    all_keys = {key for _, (_, key, _lines) in found}
    missing_keys = sorted(all_keys - existing_keys)

    if not missing_keys:
        print(f"{args.output} already covers every current setting. No changes made.")
        return

    body, total = render(sources, found, only_keys=set(missing_keys))
    section = NEW_SECTION_HEADER.format(date=datetime.date.today().isoformat())
    with open(args.output, 'a', encoding='utf-8') as handle:
        handle.write(section)
        handle.write('\n'.join(body).lstrip('\n') + '\n')
    print(f"Added {total} new setting(s) to {args.output}, live at their "
          "current tracked default value:")
    for key in missing_keys:
        print(f"  {key}")
    print("Nothing else in the file was changed.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--vars-dir', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--force', action='store_true',
                         help='Replace the file from scratch instead of only '
                              'adding new settings. Backs up the old one first.')
    args = parser.parse_args()

    if not os.path.isdir(args.vars_dir):
        sys.stderr.write(f"No such directory: {args.vars_dir}\n")
        return 1

    sources, found = collect(args.vars_dir)
    if not sources:
        sys.stderr.write(f"No settings files found in {args.vars_dir}.\n")
        return 1

    if os.path.exists(args.output) and not args.force:
        sync_additions(args, sources, found)
    else:
        write_fresh(args, sources, found)
    return 0


if __name__ == '__main__':
    sys.exit(main())
