#!/usr/bin/env python3
"""Generate a machine-local settings override file for an Ansible project.

The output lists every setting the project exposes, commented out, grouped by
the file it comes from and carrying that file's own inline comments. An
operator uncomments only what differs on their machine, so the tracked
settings files are never edited and never carry local values into a commit.

Text is copied rather than round-tripped through a YAML parser so the comments,
ordering and formatting of the source files survive intact.
"""

import argparse
import os
import re
import sys

KEY_RE = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*):')
BANNER_RE = re.compile(r'^# \d+\.\s+(.*)$')
SKIP = ('no-local-overrides.yml',)

HEADER = """---
# Machine-specific settings for this host. Generated by `make settings`.
#
# HOW THIS FILE IS USED
#   playbook.yml loads the tracked settings files first, then this one last.
#   Any key set here overrides the same key in those files. If this file does
#   not exist the project falls back to its defaults, so it is optional.
#
# THE THREE RULES
#   1. Uncomment only what differs on this machine. Everything still commented
#      keeps the tracked default, and follows it if that default ever changes.
#   2. Overriding replaces the WHOLE value, it does not merge. Uncomment a list
#      such as {list_example} and every entry must be listed here,
#      because the tracked list is replaced outright, not added to.
#   3. Once a key lives here, edit it HERE. The same key in a tracked file is
#      ignored from then on. Each run prints which keys this file supplies.
#
# This file matches *.local.yml and is gitignored, so nothing in it is ever
# committed. Git therefore does not back it up either: keep your own copy of
# anything you cannot recreate.
#
# Regenerate a fresh template with: make settings FORCE=1
# (that overwrites this file, so copy it aside first)
"""


def blocks(path):
    """Yield (banner, key, [lines]) for every top-level key in a vars file."""
    with open(path, encoding='utf-8') as handle:
        lines = handle.read().split('\n')
    banner, out, current, key = None, [], None, None
    for line in lines:
        match = BANNER_RE.match(line)
        if match:
            banner = match.group(1)
            continue
        if line.startswith('#') or not line.strip():
            if current is not None and not line.strip():
                continue
            continue
        key_match = KEY_RE.match(line)
        if key_match:
            if current is not None:
                out.append(current)
            current = (banner, key_match.group(1), [line])
            key = key_match.group(1)
        elif current is not None and (line.startswith(' ') or line.startswith('-')):
            current[2].append(line)
    if current is not None:
        out.append(current)
    return out


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--vars-dir', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--force', action='store_true')
    args = parser.parse_args()

    if os.path.exists(args.output) and not args.force:
        sys.stderr.write(
            f"Refusing to overwrite existing {args.output}.\n"
            "That file holds this machine's settings and is not backed up by git.\n"
            "Copy it aside first, then re-run with FORCE=1 to replace it.\n")
        return 1

    sources = sorted(
        f for f in os.listdir(args.vars_dir)
        if f.endswith('.yml') and not f.endswith('.local.yml') and f not in SKIP
        and not f.endswith('.example'))
    if not sources:
        sys.stderr.write(f"No settings files found in {args.vars_dir}.\n")
        return 1

    found = []
    for name in sources:
        found.extend((name, b) for b in blocks(os.path.join(args.vars_dir, name)))
    list_example = next((b[1] for _, b in found if len(b[2]) > 1), 'a list value')

    body = [HEADER.format(list_example=list_example)]
    total = 0
    for name in sources:
        entries = [b for src, b in found if src == name]
        if not entries:
            continue
        body.append('\n# ' + '=' * 75)
        body.append(f'# From {name}')
        body.append('# ' + '=' * 75)
        seen_banner = None
        for banner, key, lines in entries:
            if banner and banner != seen_banner:
                body.append(f'\n# --- {banner} ---')
                seen_banner = banner
            body.extend('# ' + line if line else '#' for line in lines)
            total += 1

    with open(args.output, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(body).rstrip('\n') + '\n')
    print(f"Wrote {args.output} with {total} settings, all commented out.")
    print("Uncomment only the ones that differ on this machine.")
    return 0


if __name__ == '__main__':
    sys.exit(main())
